### ISSUE TITLE
Show password box not working.

### ISSUE THREAD

**Issue by koentjeappel** [PACGlobalOfficial/PAC#44]
As shown in the video on gyazo you can see that the "show password" box is not working.

https://i.gyazo.com/c4978338fb8f9f53bd83d94dd9b7bad0.mp4

Just like the buttons in wallet repair ;)

**Comment by barrystyle** [comment]
Has been removed in late 0.14 series; as it is an attack vector.
Additionally, the wallet repair buttons work after the client is closed (as shown in screenshot).

![image](https://user-images.githubusercontent.com/14147070/75890833-dd8ffe80-5e69-11ea-98d4-c36aa4245079.png)
