### ISSUE TITLE
Various non-critical bugs (UI issues, wallet repair options not always starting)

### ISSUE THREAD

**Issue by CookieMonstersss** [PACGlobalOfficial/PAC#45]
1. The "Rescan blockchain files" does not appear to be doing anything on the Windows / Linus (and macOS?) qt wallets. Other "Repair wallet" functions need to be checked as well - some experienced that clicking the option (which leads to nothing happening), shutting the wallet down and starting it again triggers the execution of the desired command, some report that it doesn't.
2. General overview of the qt wallets not showing all transactions.
3. Password cannot be shown when being typed in (i.e., the "Show password" option has no effect in seemingly all cases where it occurs). Probably the same as the issue submitted a few days ago.
4. Multiple mentions of "dash" when using desktop wallet console to get help on commands.
5. UI issues (Staking toggle cut off, inability to stretch the window, unwanted (or lack of) scaling when running the wallet on screens with different resolutions).
6. Wallet reporting the version as PACGlobal version v0.14.0.6-d6fbc8bb2 while it should be PACGlobal version v0.14.0.6-d6fbc8bb24 (missing 4 at the end; present across all platforms).
7. When wallet is unlocked the option "Unlock wallet..." can be clicked on, but it does nothing. (Standard would that the option in such a situation is greyed out (or throws out an appropriate message / warning).
8. Further "bugs" (or a feature requests) for the wallets: there is a need for packaging of the binaries in the appropriate OS installers - the most issues have the macOS users, since literally everything they normally install is packed into a dmg installer format. The Linux wallet could end up on a repository. Also, the Windows (and macOS) could get an "update" feature built into the wallet itself.

**Comment by barrystyle** [comment]
1) Tested and working on latest revision. The buttons are not meant to do anything instantly; it triggers this action to occur on next wallet startup.
2) Resolved in b25ac9aa599efd6affaee5c5693d38824f6adb11
3) This feature/checkbox had been removed in late 0.14 release; as it is really an attack vector.
4) Resolved in b25ac9aa599efd6affaee5c5693d38824f6adb11
5) Resolved in new 0.15 branch.
6) Shortened commit hashes are always 9 characters long, not an important thing to report either.
7) The behaviour of this menu is quite strange; even after setting ->SetEnabled() on the item - it still appears as active - will revisit.
8) The only difference between an application packaged as it is now, vs a DMG, is a small console window staying up. If one of our community members is willing to do the Apple releases - that would be great.
